# Generated by Django 3.1.7 on 2021-04-09 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 45, 22, 255163)),
        ),
    ]
