# Generated by Django 3.1.7 on 2021-04-06 07:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210405_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserProfile',
        ),
    ]
