# Generated by Django 3.1.7 on 2021-04-09 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210409_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 56, 862011)),
        ),
    ]
