# Generated by Django 3.1.7 on 2021-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210406_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
