# Generated by Django 3.1.7 on 2021-04-09 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210409_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 17, 5, 732242)),
        ),
        migrations.CreateModel(
            name='UserFollowerTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 17, 5, 732242))),
                ('follow_id', models.ManyToManyField(related_name='the_person_being_followed', to='users.User')),
                ('follower_id', models.ManyToManyField(related_name='the_person_doing_the_following', to='users.User')),
            ],
        ),
    ]
