# Generated by Django 3.2 on 2021-04-18 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210409_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 19, 35, 50, 813295)),
        ),
        migrations.AlterField(
            model_name='userfollowertracker',
            name='date_followed',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 19, 35, 50, 813295)),
        ),
    ]
