# Generated by Django 3.2 on 2021-04-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210418_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 18, 54, 281723)),
        ),
        migrations.AlterField(
            model_name='userfollowertracker',
            name='date_followed',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 18, 54, 281723)),
        ),
    ]
