# Generated by Django 3.1.7 on 2021-04-09 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210409_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=400)),
                ('isDeliveryPossible', models.BooleanField(null=True)),
                ('deliveryTime', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 45, 22, 255163))),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('CLOTHING', 'clothing'), ('JEWELLERY', 'Jewellery'), ('SHOES', 'Shoes'), ('ART', 'Art'), ('SERVICES', 'Service')], max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 45, 22, 255163))),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('imageTwo', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('imageThree', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('imageFour', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('imageFive', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('imageSix', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'ProductsImages',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of', to='store.vendor'),
        ),
    ]
