# Generated by Django 3.1.7 on 2021-04-09 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210409_1602'),
        ('Channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 56, 862011))),
                ('chirp_image', models.ImageField(blank=True, upload_to='chirp_pics')),
                ('chirp_video', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('chirp_content', models.TextField(max_length=400)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 56, 862011))),
                ('channel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Channels.channel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChirpPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_title', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 56, 862011))),
                ('agree_count', models.IntegerField(default=0)),
                ('disagree_count', models.IntegerField(default=0)),
                ('chirp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chirps.chirp')),
            ],
            options={
                'verbose_name_plural': 'ChirpPolls',
            },
        ),
        migrations.CreateModel(
            name='ChirpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, upload_to='chirpimage/%Y/%m/%d /')),
                ('image_two', models.ImageField(blank=True, upload_to='chirpimage/%Y/%m/%d /')),
                ('chirp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chirps.chirp')),
            ],
            options={
                'verbose_name_plural': 'ChirpImages',
            },
        ),
    ]
