# Generated by Django 3.2 on 2021-04-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chirps', '0003_auto_20210418_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 18, 54, 288992)),
        ),
        migrations.AlterField(
            model_name='chirp',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 18, 54, 288992)),
        ),
        migrations.AlterField(
            model_name='chirppoll',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 18, 54, 288992)),
        ),
    ]
