# Generated by Django 3.1.7 on 2021-04-09 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20210409_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 56, 862011))),
                ('no_of_subscribers', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSubscriberTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscribed', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 56, 862011))),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Channels.channel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name_plural': 'ChannelSubscriberTrackers',
            },
        ),
    ]
