# Generated by Django 3.2 on 2021-04-18 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channels', '0002_auto_20210409_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 19, 35, 50, 818478)),
        ),
        migrations.AlterField(
            model_name='channelsubscribertracker',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 19, 35, 50, 818478)),
        ),
    ]
